# Generated by Django 5.2 on 2026-05-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Intermediário'), (3, 'Avançado')], max_length=1, verbose_name='Nivel do Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20, verbose_name='Sexo'),
        ),
    ]
