# Generated by Django 5.2 on 2026-07-08 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='objetivo',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='cadastros.pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
