# Generated by Django 5.2 on 2026-09-15 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_pessoa_cpf_alter_pessoa_objetivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='cadastros.pessoa')),
                ('professor_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='cadastros.pessoa')),
                ('professor_novo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='cadastros.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
