# Generated by Django 5.2 on 2026-09-15 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_transferenciaaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciaaluno',
            name='origem',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], default='PROFESSOR', max_length=10, verbose_name='Solicitado por'),
        ),
        migrations.AlterField(
            model_name='transferenciaaluno',
            name='professor_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='cadastros.pessoa'),
        ),
    ]
