# Generated by Django 5.2 on 2026-09-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_transferenciaaluno_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciaaluno',
            name='origem',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], default='PROFESSOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='transferenciaaluno',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada'), ('EXPIRADA', 'Expirada (sem resposta)')], default='PENDENTE', max_length=10),
        ),
    ]
