# Generated by Django 5.2 on 2026-05-20 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.FloatField(verbose_name='Altura')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('cintura', models.FloatField(verbose_name='Cintura')),
                ('quadril', models.FloatField(verbose_name='Quadril')),
                ('bracoDireito', models.FloatField(verbose_name='Braço Direito')),
                ('bracoEsquerdo', models.FloatField(verbose_name='Braço Esquerdo')),
                ('coxaDireita', models.FloatField(verbose_name='Coxa Direita')),
                ('coxaEsquerda', models.FloatField(verbose_name='Coxa Esquerda')),
                ('panturrilhaDireita', models.FloatField(verbose_name='Panturrilha Direita')),
                ('panturrilhaEsquerda', models.FloatField(verbose_name='Panturrilha Esquerda')),
                ('peito', models.FloatField(verbose_name='Peito')),
                ('dataMedida', models.DateField(verbose_name='Data da medida')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.aluno')),
            ],
        ),
    ]
