# Generated by Django 5.2 on 2026-07-30 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_alter_pessoa_cpf_alter_pessoa_objetivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('altura', models.FloatField(verbose_name='Altura')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('cintura', models.FloatField(verbose_name='Cintura')),
                ('quadril', models.FloatField(verbose_name='Quadril')),
                ('braco_direito', models.FloatField(verbose_name='Braço Direito')),
                ('braco_esquerdo', models.FloatField(verbose_name='Braço Esquerdo')),
                ('coxa_direita', models.FloatField(verbose_name='Coxa Direita')),
                ('coxa_esquerda', models.FloatField(verbose_name='Coxa Esquerda')),
                ('panturrilha_direita', models.FloatField(verbose_name='Panturrilha Direita')),
                ('panturrilha_esquerda', models.FloatField(verbose_name='Panturrilha Esquerda')),
                ('peito', models.FloatField(verbose_name='Peito')),
                ('data_medida', models.DateField(verbose_name='Data da medida')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidas_aluno', to='cadastros.pessoa')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastrado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
