# Generated by Django 5.2 on 2026-09-17 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0004_transferenciaaluno_origem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Dia da semana')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aluno', to='cadastros.pessoa')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_professor', to='cadastros.pessoa')),
            ],
            options={
                'ordering': ['dia_semana', 'horario'],
                'unique_together': {('professor', 'dia_semana', 'horario')},
            },
        ),
    ]
