# Generated by Django 5.2 on 2026-07-30 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_alter_pessoa_cpf_alter_pessoa_objetivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Exercicio')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercicio.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome_treino', models.CharField(max_length=20, verbose_name='Nome do Treino')),
                ('data_inicio', models.DateField(verbose_name='Data de Inicio')),
                ('data_fim', models.DateField(verbose_name='Data de Encerramento')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Treinos', to='cadastros.pessoa')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExercicioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('series', models.IntegerField(verbose_name='Séries')),
                ('repeticoes', models.IntegerField(verbose_name='Repetições')),
                ('descanso', models.IntegerField(verbose_name='Descanso')),
                ('peso_atual', models.FloatField(verbose_name='Peso Atual')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercicio.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercicio_do_treino', to='exercicio.treino')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
