# Generated by Django 5.2 on 2026-05-06 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Exercicio')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercicio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTreino', models.CharField(max_length=20, verbose_name='Nome do Treino')),
                ('dataInicio', models.DateField(verbose_name='Data de Inicio')),
                ('dataFim', models.DateField(verbose_name='Data de Encerramento')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cadastradoEm', models.DateTimeField(verbose_name='Cadastrado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.aluno')),
                ('cadastradoPor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ExericioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(verbose_name='Séries')),
                ('repeticoes', models.IntegerField(verbose_name='Repetições')),
                ('descanso', models.IntegerField(verbose_name='Descanso')),
                ('cadastraoEm', models.DateField(verbose_name='Cadastrado em')),
                ('pesoAtual', models.FloatField(verbose_name='Peso Atual')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercicio.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercicio.treino')),
            ],
        ),
    ]
