# Generated by Django 5.2 on 2026-05-20 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExericioTreino',
            new_name='ExercicioTreino',
        ),
    ]
