# Generated by Django 5.2 on 2026-05-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_aluno_nivel_alter_aluno_sexo'),
        ('exercicio', '0002_rename_exericiotreino_exerciciotreino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciciotreino',
            old_name='cadastraoEm',
            new_name='cadatradoEm',
        ),
        migrations.AlterField(
            model_name='exerciciotreino',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercicio_do_treino', to='exercicio.treino'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Treinos', to='cadastros.aluno'),
        ),
    ]
